# # name of workflow
# name: Hello World Workflow

# # specify event that this will apply
# on:
#   push:
#     branches: [main]

# # then define jobs that needs to be executed
# jobs:
#   say_hello: # job name
#     runs-on: ubuntu_latest # which image should be loaded on that server
#     steps:
#       - name: Print Hello World # step name
#         run: echo "Hello, world!"

name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # make workflow get access to github repo

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domain: domain.com
          working-directory: ./
          vercel-args: "--prod"

#comment

# name: Abdularhman
# age: 22
# skills:
#   - Frontend
#   - Backend
#   - Fullstack

# sentence: "hello"

# literal: |
#   this is a block of text.
#   this text will have
#   line breaks

# specify event that this will apply
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branch: [main]

